# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SDM.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SDM(object):
    def setupUi(self, SDM):
        SDM.setObjectName("SDM")
        SDM.resize(777, 711)
        self.centralwidget = QtWidgets.QWidget(SDM)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ipBox = QtWidgets.QComboBox(self.centralwidget)
        self.ipBox.setEditable(True)
        self.ipBox.setObjectName("ipBox")
        self.gridLayout_2.addWidget(self.ipBox, 1, 1, 1, 3)
        self.usbtmcBox = QtWidgets.QComboBox(self.centralwidget)
        self.usbtmcBox.setObjectName("usbtmcBox")
        self.gridLayout_2.addWidget(self.usbtmcBox, 2, 1, 1, 2)
        self.statusbar = QtWidgets.QLabel(self.centralwidget)
        self.statusbar.setText("")
        self.statusbar.setObjectName("statusbar")
        self.gridLayout_2.addWidget(self.statusbar, 5, 0, 1, 5)
        self.strCheckBox = QtWidgets.QRadioButton(self.centralwidget)
        self.strCheckBox.setChecked(True)
        self.strCheckBox.setObjectName("strCheckBox")
        self.gridLayout_2.addWidget(self.strCheckBox, 0, 2, 1, 1)
        self.intCheckBox = QtWidgets.QRadioButton(self.centralwidget)
        self.intCheckBox.setObjectName("intCheckBox")
        self.gridLayout_2.addWidget(self.intCheckBox, 0, 3, 1, 1)
        self.rescanButton = QtWidgets.QPushButton(self.centralwidget)
        self.rescanButton.setObjectName("rescanButton")
        self.gridLayout_2.addWidget(self.rescanButton, 0, 4, 1, 1)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_2.addWidget(self.connectButton, 0, 0, 1, 1)
        self.comPortBox = QtWidgets.QComboBox(self.centralwidget)
        self.comPortBox.setObjectName("comPortBox")
        self.gridLayout_2.addWidget(self.comPortBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 3, 1, 2)
        self.useIPButton = QtWidgets.QPushButton(self.centralwidget)
        self.useIPButton.setObjectName("useIPButton")
        self.gridLayout_2.addWidget(self.useIPButton, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 4, 1, 1)
        self.connect_usbtmc_Button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_usbtmc_Button.setObjectName("connect_usbtmc_Button")
        self.gridLayout_2.addWidget(self.connect_usbtmc_Button, 2, 0, 1, 1)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setObjectName("quitButton")
        self.gridLayout_2.addWidget(self.quitButton, 4, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.outTab = QtWidgets.QWidget()
        self.outTab.setObjectName("outTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.output_box = QtWidgets.QTextEdit(self.outTab)
        self.output_box.setObjectName("output_box")
        self.gridLayout_3.addWidget(self.output_box, 5, 0, 1, 7)
        self.activeDeviceBox = QtWidgets.QComboBox(self.outTab)
        self.activeDeviceBox.setObjectName("activeDeviceBox")
        self.gridLayout_3.addWidget(self.activeDeviceBox, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.outTab)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.outTab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 2)
        self.clearButton = QtWidgets.QPushButton(self.outTab)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_3.addWidget(self.clearButton, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(213, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(263, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 6, 1, 1, 5)
        self.saveButton = QtWidgets.QPushButton(self.outTab)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout_3.addWidget(self.saveButton, 6, 6, 1, 1)
        self.fileCommands = QtWidgets.QPushButton(self.outTab)
        self.fileCommands.setObjectName("fileCommands")
        self.gridLayout_3.addWidget(self.fileCommands, 2, 6, 1, 1)
        self.infoLabel = QtWidgets.QLabel(self.outTab)
        self.infoLabel.setText("")
        self.infoLabel.setObjectName("infoLabel")
        self.gridLayout_3.addWidget(self.infoLabel, 3, 0, 1, 7)
        self.executeCmdsButton = QtWidgets.QPushButton(self.outTab)
        self.executeCmdsButton.setObjectName("executeCmdsButton")
        self.gridLayout_3.addWidget(self.executeCmdsButton, 2, 4, 1, 1)
        self.sendButton = QtWidgets.QPushButton(self.outTab)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout_3.addWidget(self.sendButton, 2, 0, 1, 2)
        self.queryButton = QtWidgets.QPushButton(self.outTab)
        self.queryButton.setObjectName("queryButton")
        self.gridLayout_3.addWidget(self.queryButton, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.outTab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.command_entry = QtWidgets.QComboBox(self.outTab)
        self.command_entry.setEditable(True)
        self.command_entry.setObjectName("command_entry")
        self.gridLayout_3.addWidget(self.command_entry, 1, 0, 1, 7)
        self.tabWidget.addTab(self.outTab, "")
        self.comTab = QtWidgets.QWidget()
        self.comTab.setObjectName("comTab")
        self.gridLayout = QtWidgets.QGridLayout(self.comTab)
        self.gridLayout.setObjectName("gridLayout")
        self.com_params_widget = SerialPortWidget(self.comTab)
        self.com_params_widget.setObjectName("com_params_widget")
        self.gridLayout.addWidget(self.com_params_widget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.comTab, "")
        self.commands_tab = QtWidgets.QWidget()
        self.commands_tab.setObjectName("commands_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.commands_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.commands_view = QtWidgets.QTextEdit(self.commands_tab)
        self.commands_view.setObjectName("commands_view")
        self.gridLayout_4.addWidget(self.commands_view, 0, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.commands_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.delay_between_commands_box = QtWidgets.QSpinBox(self.commands_tab)
        self.delay_between_commands_box.setProperty("value", 1)
        self.delay_between_commands_box.setObjectName("delay_between_commands_box")
        self.gridLayout_4.addWidget(self.delay_between_commands_box, 1, 1, 1, 1)
        self.tabWidget.addTab(self.commands_tab, "")
        self.exp_tab = QtWidgets.QWidget()
        self.exp_tab.setObjectName("exp_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.exp_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.end_file_Button = QtWidgets.QPushButton(self.exp_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_file_Button.sizePolicy().hasHeightForWidth())
        self.end_file_Button.setSizePolicy(sizePolicy)
        self.end_file_Button.setObjectName("end_file_Button")
        self.gridLayout_5.addWidget(self.end_file_Button, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.exp_tab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.init_file_Button = QtWidgets.QPushButton(self.exp_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.init_file_Button.sizePolicy().hasHeightForWidth())
        self.init_file_Button.setSizePolicy(sizePolicy)
        self.init_file_Button.setObjectName("init_file_Button")
        self.gridLayout_5.addWidget(self.init_file_Button, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.exp_tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.active_exp_devBox = QtWidgets.QComboBox(self.exp_tab)
        self.active_exp_devBox.setObjectName("active_exp_devBox")
        self.gridLayout_5.addWidget(self.active_exp_devBox, 0, 1, 1, 2)
        self.save_exp_btn = QtWidgets.QPushButton(self.exp_tab)
        self.save_exp_btn.setObjectName("save_exp_btn")
        self.gridLayout_5.addWidget(self.save_exp_btn, 5, 0, 1, 1)
        self.clear_exp_btn = QtWidgets.QPushButton(self.exp_tab)
        self.clear_exp_btn.setObjectName("clear_exp_btn")
        self.gridLayout_5.addWidget(self.clear_exp_btn, 5, 3, 1, 1)
        self.execute_end = QtWidgets.QPushButton(self.exp_tab)
        self.execute_end.setObjectName("execute_end")
        self.gridLayout_5.addWidget(self.execute_end, 4, 3, 1, 1)
        self.exec_file_Button = QtWidgets.QPushButton(self.exp_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exec_file_Button.sizePolicy().hasHeightForWidth())
        self.exec_file_Button.setSizePolicy(sizePolicy)
        self.exec_file_Button.setObjectName("exec_file_Button")
        self.gridLayout_5.addWidget(self.exec_file_Button, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.exp_tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.exp_tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 0, 1, 1)
        self.exp_output_box = QtWidgets.QTextEdit(self.exp_tab)
        self.exp_output_box.setObjectName("exp_output_box")
        self.gridLayout_5.addWidget(self.exp_output_box, 6, 0, 1, 4)
        self.expIterEntry = QtWidgets.QLineEdit(self.exp_tab)
        self.expIterEntry.setInputMask("")
        self.expIterEntry.setText("")
        self.expIterEntry.setObjectName("expIterEntry")
        self.gridLayout_5.addWidget(self.expIterEntry, 5, 1, 1, 2)
        self.initfileLabel = QtWidgets.QLabel(self.exp_tab)
        self.initfileLabel.setObjectName("initfileLabel")
        self.gridLayout_5.addWidget(self.initfileLabel, 1, 2, 1, 1)
        self.expfileLabel = QtWidgets.QLabel(self.exp_tab)
        self.expfileLabel.setObjectName("expfileLabel")
        self.gridLayout_5.addWidget(self.expfileLabel, 2, 2, 1, 1)
        self.endfileLabel = QtWidgets.QLabel(self.exp_tab)
        self.endfileLabel.setObjectName("endfileLabel")
        self.gridLayout_5.addWidget(self.endfileLabel, 4, 2, 1, 1)
        self.execute_init = QtWidgets.QPushButton(self.exp_tab)
        self.execute_init.setObjectName("execute_init")
        self.gridLayout_5.addWidget(self.execute_init, 1, 3, 1, 1)
        self.execute_exp = QtWidgets.QPushButton(self.exp_tab)
        self.execute_exp.setObjectName("execute_exp")
        self.gridLayout_5.addWidget(self.execute_exp, 2, 3, 1, 1)
        self.use_cycle_box = QtWidgets.QCheckBox(self.exp_tab)
        self.use_cycle_box.setObjectName("use_cycle_box")
        self.gridLayout_5.addWidget(self.use_cycle_box, 3, 0, 1, 2)
        self.cycle_prams_btn = QtWidgets.QPushButton(self.exp_tab)
        self.cycle_prams_btn.setObjectName("cycle_prams_btn")
        self.gridLayout_5.addWidget(self.cycle_prams_btn, 3, 3, 1, 1)
        self.tabWidget.addTab(self.exp_tab, "")
        self.cycle_tab = QtWidgets.QWidget()
        self.cycle_tab.setObjectName("cycle_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.cycle_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.return_exp_btn = QtWidgets.QPushButton(self.cycle_tab)
        self.return_exp_btn.setObjectName("return_exp_btn")
        self.gridLayout_8.addWidget(self.return_exp_btn, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.counts_radio = QtWidgets.QRadioButton(self.cycle_tab)
        self.counts_radio.setChecked(True)
        self.counts_radio.setObjectName("counts_radio")
        self.gridLayout_6.addWidget(self.counts_radio, 0, 0, 1, 1)
        self.counts_box = QtWidgets.QSpinBox(self.cycle_tab)
        self.counts_box.setProperty("value", 1)
        self.counts_box.setObjectName("counts_box")
        self.gridLayout_6.addWidget(self.counts_box, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.cycle_tab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_8.addWidget(self.label_14, 1, 1, 1, 1)
        self.delay_scripts_box = QtWidgets.QSpinBox(self.cycle_tab)
        self.delay_scripts_box.setObjectName("delay_scripts_box")
        self.gridLayout_8.addWidget(self.delay_scripts_box, 1, 2, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.step_radio = QtWidgets.QRadioButton(self.cycle_tab)
        self.step_radio.setObjectName("step_radio")
        self.gridLayout_7.addWidget(self.step_radio, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(508, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.cycle_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem5 = QtWidgets.QSpacerItem(20, 161, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 3, 1, 1, 1)
        self.step_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.step_box.setProperty("value", 0.25)
        self.step_box.setObjectName("step_box")
        self.gridLayout_9.addWidget(self.step_box, 0, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(137, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 7, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(242, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem7, 1, 5, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 5, 1, 1)
        self.from_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.from_box.setObjectName("from_box")
        self.gridLayout_9.addWidget(self.from_box, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 0, 2, 1, 2)
        self.to_box = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.to_box.setProperty("value", 1.0)
        self.to_box.setObjectName("to_box")
        self.gridLayout_9.addWidget(self.to_box, 0, 4, 1, 1)
        self.out_variable_box = QtWidgets.QCheckBox(self.groupBox)
        self.out_variable_box.setChecked(True)
        self.out_variable_box.setObjectName("out_variable_box")
        self.gridLayout_9.addWidget(self.out_variable_box, 2, 0, 1, 1)
        self.entry_separator_box = QtWidgets.QLineEdit(self.groupBox)
        self.entry_separator_box.setObjectName("entry_separator_box")
        self.gridLayout_9.addWidget(self.entry_separator_box, 2, 1, 1, 4)
        self.replace_variable_box = QtWidgets.QCheckBox(self.groupBox)
        self.replace_variable_box.setChecked(True)
        self.replace_variable_box.setObjectName("replace_variable_box")
        self.gridLayout_9.addWidget(self.replace_variable_box, 1, 0, 1, 1)
        self.var_box = QtWidgets.QLineEdit(self.groupBox)
        self.var_box.setObjectName("var_box")
        self.gridLayout_9.addWidget(self.var_box, 1, 1, 1, 4)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 2, 5, 1, 3)
        self.gridLayout_7.addWidget(self.groupBox, 1, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_7, 2, 0, 1, 3)
        self.tabWidget.addTab(self.cycle_tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 3, 0, 1, 5)
        SDM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SDM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 35))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SDM.setMenuBar(self.menubar)
        self.actionClose = QtWidgets.QAction(SDM)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionClose)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SDM)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SDM)

    def retranslateUi(self, SDM):
        _translate = QtCore.QCoreApplication.translate
        SDM.setWindowTitle(_translate("SDM", "Simple Device Monitor"))
        self.strCheckBox.setText(_translate("SDM", "As Strings"))
        self.intCheckBox.setText(_translate("SDM", "As Integers"))
        self.rescanButton.setText(_translate("SDM", "Rescan ports"))
        self.connectButton.setText(_translate("SDM", "Connect to .."))
        self.label_5.setText(_translate("SDM", "Just for USBTMC devices (Linux only)"))
        self.useIPButton.setText(_translate("SDM", "Connect to .."))
        self.label_3.setText(_translate("SDM", "Just for TCP devices."))
        self.connect_usbtmc_Button.setText(_translate("SDM", "Connect to ..."))
        self.quitButton.setText(_translate("SDM", "Exit"))
        self.label_4.setText(_translate("SDM", "Active device:"))
        self.label_2.setText(_translate("SDM", "Output Box:"))
        self.clearButton.setText(_translate("SDM", "Clear"))
        self.saveButton.setText(_translate("SDM", "Save"))
        self.fileCommands.setText(_translate("SDM", "Commands from file ..."))
        self.executeCmdsButton.setText(_translate("SDM", "Execute ..."))
        self.sendButton.setText(_translate("SDM", "Send(Write)"))
        self.queryButton.setText(_translate("SDM", "Query(Ask)"))
        self.label.setText(_translate("SDM", "Command to send:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outTab), _translate("SDM", "Outputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comTab), _translate("SDM", "COM parameters"))
        self.label_6.setText(_translate("SDM", "Delay between commands:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.commands_tab), _translate("SDM", "Loaded commands"))
        self.end_file_Button.setText(_translate("SDM", "File?"))
        self.label_7.setText(_translate("SDM", "Init file:"))
        self.init_file_Button.setText(_translate("SDM", "File?"))
        self.label_8.setText(_translate("SDM", "Device to work with:"))
        self.save_exp_btn.setText(_translate("SDM", "Save"))
        self.clear_exp_btn.setText(_translate("SDM", "Clear"))
        self.execute_end.setText(_translate("SDM", "Execute"))
        self.exec_file_Button.setText(_translate("SDM", "File?"))
        self.label_10.setText(_translate("SDM", "End file:"))
        self.label_9.setText(_translate("SDM", "Execute commands:"))
        self.expIterEntry.setPlaceholderText(_translate("SDM", "EntryBox"))
        self.initfileLabel.setText(_translate("SDM", "?"))
        self.expfileLabel.setText(_translate("SDM", "?"))
        self.endfileLabel.setText(_translate("SDM", "?"))
        self.execute_init.setText(_translate("SDM", "Execute"))
        self.execute_exp.setText(_translate("SDM", "Execute"))
        self.use_cycle_box.setText(_translate("SDM", "Use Cycle?"))
        self.cycle_prams_btn.setText(_translate("SDM", "Cycle parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exp_tab), _translate("SDM", "Basic exeriment set-up"))
        self.return_exp_btn.setText(_translate("SDM", "Return to experiment"))
        self.counts_radio.setText(_translate("SDM", "Counts"))
        self.label_14.setText(_translate("SDM", "Delay between scripts"))
        self.step_radio.setText(_translate("SDM", "Steps from to"))
        self.groupBox.setTitle(_translate("SDM", "Stepping parameters"))
        self.label_13.setText(_translate("SDM", "Step"))
        self.label_11.setText(_translate("SDM", "From"))
        self.label_12.setText(_translate("SDM", "To"))
        self.out_variable_box.setText(_translate("SDM", "Output a step value into EntryBox"))
        self.entry_separator_box.setText(_translate("SDM", ";"))
        self.replace_variable_box.setText(_translate("SDM", "Replace variable by step value:"))
        self.var_box.setText(_translate("SDM", "{x}"))
        self.label_15.setText(_translate("SDM", "<== Separator for EntryBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cycle_tab), _translate("SDM", "Cycle parameters"))
        self.menuFile.setTitle(_translate("SDM", "Fi&le"))
        self.actionClose.setText(_translate("SDM", "Close"))

from GUI.serialPlotWidget.serialPortWidget import SerialPortWidget
